[package]
name = "calculator"
version = "0.1.0"
edition = "2018"
authors = ["Novax86 (David Moor)", "moorcode66@yahoo.com"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
